name = "proxytelegram12"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB" # این باید دقیقاً کلمه DB با حروف بزرگ باشد
database_name = "souq_db"
database_id = "شناسه_دیتابیس_شما"
