name = "proxytelegram12"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
BOT_TOKEN = "8587925383:AAElQXNbZ8YIDJMWwX4YyVFMCOsC2pV6H6c"
MINI_APP_URL = "https://proxytelegram12.mehdi11eidani.workers.dev/"

[[d1_databases]]
binding = "DB"
database_name = "souq_db"
database_id = "b2c8617e-fa35-4ef2-84f9-45c72c65d432"
